### ISSUE TITLE
Add validation messages to signup page

### ISSUE THREAD

**Issue by vishnuvnathan** [vishnusnathann/nyt-news-app#1]
### Add validation messages to signup page

Add proper validation message to signup page with error messages.

**Comment by Sakshi-75** [comment]
Hi @vishnusnathann ,
Can I work on this?

**Comment by vishnuvnathan** [comment]
@Sakshi-75 Sure

**Comment by Sakshi-75** [comment]
Hi @vishnusnathann ,
Should I add more validations to the fields like min length for password and regex on email?
Also, I can see that currently the error messages are being shown in 3 different ways:
1. Pop up - password mismatch
2. Red error message under the field - Email already exists
3. Pop up prompt on the field - Special characters not allowed
So, do we want to keep all these different ways of showing errors or do we want to show all errors in a single format?
And if single format, then which one?

**Comment by vishnuvnathan** [comment]
@Sakshi-75 Thanks for you deep observation.
You can use any form validation library like react-hook-form or Formik.

**Comment by vishnuvnathan** [comment]
Hi @Sakshi-75 any updates? Do you need my help?

**Comment by Sakshi-75** [comment]
Hi @vishnusnathann , 
Sorry I didn't get a chance to work on this due to some other tasks on hand. Will work on it today. I'll let you know if I need any help, thanks. 😊

**Comment by Sakshi-75** [comment]
Hi @vishnusnathann ,
I've raised a PR for this: https://github.com/vishnusnathann/nyt-news-app/pull/5
Please review it.
Also, in case you approve it can you add the HACKTOBERFEST-ACCEPTED label to it?
Thanks!
