### ISSUE TITLE
Add validation message to login page

### ISSUE THREAD

**Issue by vishnuvnathan** [vishnusnathann/nyt-news-app#2]
### Add validation message to login page

Add proper validation error message to login page.

**Comment by gaut2003** [comment]
Assign this to me.

**Comment by theadityaagnihotri** [comment]
can i work on this?

**Comment by utkarsh4321** [comment]
can you assign this to me?

**Comment by sivasuriyankumarasamy** [comment]
Hi @vishnusnathann,

I would like to work on this. Can you please assign this to me

**Comment by sivasuriyankumarasamy** [comment]
Hi @vishnusnathann,

I have raised a PR for this ticket. Kindly review.
https://github.com/vishnusnathann/nyt-news-app/pull/4

Also, in case you approve it can you add the HACKTOBERFEST-ACCEPTED label to it?
Thanks!
